*** Settings ***
Library     ${CURDIR}/../utils/CustomLibrary.py
Library     SeleniumLibrary    screenshot_root_directory=${CURDIR}${/}..${/}..${/}results${/}screenshots
library     OperatingSystem
library     Collections
library     String
library     DateTime
library     Dialogs
library     OperatingSystem
library     Collections
library     String
library     DateTime
library     Dialogs    
library     RequestsLibrary